frontend/components/app.jsx, frontend/components/main.jsx, frontend/components/nav.jsx, frontend/components/root.jsx, package.json
Adds a main page with the table locks
Adds styled-components and font-awesome dependencies.
=> add main page with table locks

frontend/components/main.jsx, frontend/constants.js
* fixes bug where first 5 locks are unclickable
* add padding
* use colors slightly easier on the eyes and move to a constant
* add middle lock, conditional on whether the other locks are open
=> improve main lock layout

frontend/components/app.jsx, frontend/components/main.jsx, frontend/components/puzzle.jsx, frontend/components/puzzle1.jsx, package.json
Open to suggestions on how to organize this, but I'm having App manage the socket and pass it to the child components to be able to send/receive messages.
TODO:
server stuff coming in a separate PR
Don't think the submit on Puzzle1 works yet, will have to figure out why
=> integrate socket.io

frontend/components/main.jsx, server/server.py
actually set up game state now and have the main table with locks respond to it
=> have table respond to game state

server/server.py
Now, after running the server, you can visit `127.0.0.1:8000`
=> serve static files through python so chrome can attach cookies to URL

frontend/components/puzzle.jsx, frontend/components/puzzle2.jsx, server/server.py
Wrapper puzzle creates a state property incorrect answer after wrong answer submit that gets passed down to lower level puzzle component where an if statement will render red border on input type by using document.getElementById
=> WIP - Pewpew wrapperpuzzle work

frontend/components/app.jsx, package.json, server/server.py
=> add toasters when players join

.eslintrc.json, frontend/components/app.jsx, frontend/components/main.jsx, frontend/components/puzzle5.jsx, frontend/components/puzzleHeader.jsx, frontend/components/root.jsx, frontend/wrappers.jsx, package.json, server/server.py
Players can now press this big button to change the color of each icon, which syncs across all screens with puzzle 5 open
=> implement improvements to puzzle 5

frontend/components/puzzle5.jsx
=> style puzzle5 better

frontend/components/buttonContants.jsx, frontend/components/puzzle4.jsx, package-lock.json, server/server.py
Have not added the disabling ability on this puzzle. Want to merge with master then pull with an updated puzzle 1 and 2 before adding the disable functionality
=> Working Puzzle 4 without the disable/enable based on other puzzles

server/server.py
was using `send_game_state` with sid and table arguments, but they are different things and we used `GAME_STATE[table]`, which assumed the parameter passed in was a table number.
=> fix refresh bug attempt 2

frontend/components/app.jsx, frontend/components/puzzle1.jsx, frontend/components/root.jsx, frontend/components/welcomeHeader.jsx, frontend/css/style.css, frontend/thehunt.html
add viewport for mobile browsers (https://github.com/iamsammak/thehuntgame/issues/36)
clean up some styles
=> make things more mobile friendly

frontend/components/switch.jsx
=> add switch component

frontend/components/person6.jsx, frontend/components/puzzle6.jsx, frontend/components/root.jsx
=> add puzzle6

frontend/components/root.jsx
no more having to add individual icons to the library, now they're all in the library!
https://github.com/iamsammak/thehuntgame/issues/64
=> make font awesome easier to work with

frontend/components/person1.jsx, frontend/components/person2.jsx, frontend/components/person3.jsx, frontend/components/person4.jsx, frontend/components/person5.jsx, frontend/components/person6.jsx, frontend/components/person7.jsx, frontend/components/puzzle7.jsx, frontend/components/puzzle7Clue.jsx, frontend/components/switch.jsx, server/server.py
fixes https://github.com/iamsammak/thehuntgame/issues/51
=> implement puzzle 7

frontend/components/person3.jsx, frontend/components/puzzle8.jsx
fixes https://github.com/iamsammak/thehuntgame/issues/52
=> implement puzzle8

frontend/components/emptyBody.jsx, frontend/components/person0.jsx, frontend/components/person1.jsx, frontend/components/person2.jsx, frontend/components/person3.jsx, frontend/components/person4.jsx, frontend/components/person5.jsx, frontend/components/person6.jsx, frontend/components/person7.jsx, frontend/components/personHeader.jsx, frontend/helpers.js
* wire up puzzles 1-4
* improve header and empty body and make them easier to change the names and images later
=> some updates

.eslintrc.json, frontend/components/emptyBody.jsx, frontend/components/person0.jsx, frontend/components/personHeader.jsx, frontend/components/puzzle.jsx, frontend/components/puzzle1.jsx, frontend/components/puzzle2.jsx, frontend/components/puzzle3.jsx, frontend/components/puzzle4.jsx, frontend/components/welcomeHeader.jsx
just some clean up items
* add some eslint rules
* newlines, commas, semicolons
=> some cleanup

frontend/components/buttonContants.jsx, frontend/components/home.jsx, frontend/components/main.jsx
I rebased my original edits from old master to Andy's "add-finish-state" branch to account for the cleanup code changes.
Which is why this is set to merge to alau.add-finish-state
Added Chervon Up and Down buttons
=> Table numbers off add finish state

frontend/components/app.jsx, frontend/components/base.jsx, frontend/components/finish.jsx, frontend/components/person0.jsx, frontend/components/person1.jsx, frontend/components/person2.jsx, frontend/components/person3.jsx, frontend/components/person4.jsx, frontend/components/person5.jsx, frontend/components/person6.jsx, frontend/components/person7.jsx, frontend/components/puzzle1.jsx, frontend/components/puzzle2.jsx, frontend/components/puzzle3.jsx, frontend/components/puzzle4.jsx, frontend/components/puzzle4Clue.jsx, frontend/components/puzzle5.jsx, frontend/components/puzzle5Clue.jsx, frontend/components/puzzle6.jsx, frontend/components/puzzle7.jsx, frontend/components/puzzle8.jsx, frontend/components/submit.jsx, frontend/helpers.js, frontend/wrappers.jsx, server/server.py
sorry this is a huge one. basically adds the text to the puzzles and puts the puzzles in the right places
=> implement game flow

package.json
actually recursively lint files
add lint-fix
=> improve linter

frontend/components/puzzle4.jsx, frontend/components/puzzle8.jsx
=> add error states to puzzle 4 and 8

frontend/components/finish.jsx
=> update finish state

frontend/components/person0.jsx, frontend/components/person2.jsx, frontend/components/person3.jsx, frontend/components/person4.jsx, frontend/components/person5.jsx, frontend/components/person6.jsx
ran through the sheet again and updated a bunch of persons
=> update person bodies

frontend/components/app.jsx, frontend/components/home.jsx
This is to fix Issue #98 can't increment or decrement (specifically in Firefox)
=> Fix button issue

frontend/components/person6.jsx, frontend/components/puzzle1.jsx, frontend/components/puzzle2.jsx, frontend/components/puzzle3.jsx, frontend/components/puzzle4.jsx, frontend/components/puzzle5.jsx, frontend/components/puzzle6.jsx, frontend/components/puzzle7.jsx, frontend/components/puzzleA.jsx, frontend/helpers.js, server/server.py
also had to move all puzzles to be string keys in game state
=> add puzzleA

frontend/components/buttonContants.jsx, frontend/components/person7.jsx, frontend/components/puzzle4.jsx, frontend/components/puzzleB.jsx, frontend/constants.js
=> add puzzleB

server/server.py
fixes https://github.com/iamsammak/thehuntgame/issues/116
fixes https://github.com/iamsammak/thehuntgame/issues/127
=> update some server defaults

frontend/components/hint.jsx, frontend/components/person0.jsx, server/server.py
puzzles need to be strings
also hides hints when we don't have one
fixes https://github.com/iamsammak/thehuntgame/issues/122
=> fix hint shown

frontend/components/person0.jsx, frontend/components/person1.jsx, frontend/components/person2.jsx, frontend/components/person3.jsx, frontend/components/person4.jsx, frontend/components/person5.jsx, frontend/components/person6.jsx, frontend/components/person7.jsx, frontend/components/puzzle5.jsx, frontend/components/puzzle5Clue.jsx
fixes https://github.com/iamsammak/thehuntgame/issues/124
=> fix same name for puzzle5

frontend/components/puzzleA.jsx, frontend/components/puzzleB.jsx
fixes https://github.com/iamsammak/thehuntgame/issues/123
=> hide inputs for puzzle A and B when complete

frontend/components/puzzle6.jsx
fixes https://github.com/iamsammak/thehuntgame/issues/125
=> put puzzle 6 in the solved position when it's solved

server/server.py
fixes https://github.com/iamsammak/thehuntgame/issues/130
=> redirect user to finish state when joining a finished table

frontend/components/admin.jsx, frontend/components/hint.jsx, server/server.py
issue #128 
issue #119 
issue #118
=> Admin minor fixes

frontend/components/buttonContants.jsx, frontend/components/home.jsx
by default buttons' have a 1px black border - I removed that
=> fix border pixel issue

frontend/components/puzzle8.jsx, frontend/components/root.jsx
fixes https://github.com/iamsammak/thehuntgame/issues/150
=> puzzle8 updates

frontend/components/hint.jsx
related to https://github.com/iamsammak/thehuntgame/issues/144
=> update hint text

frontend/components/puzzle7.jsx, frontend/wrappers.jsx, server/server.py
only allows one submission per table per minute
related to https://github.com/iamsammak/thehuntgame/issues/151
=> restrict brute forcing of puzzle7

frontend/components/app.jsx, frontend/components/base.jsx, frontend/components/main.jsx, frontend/components/person.jsx, frontend/components/person0.jsx, frontend/components/person1.jsx, frontend/components/person2.jsx, frontend/components/person3.jsx, frontend/components/person4.jsx, frontend/components/person5.jsx, frontend/components/person6.jsx, frontend/components/person7.jsx, frontend/components/personHeader.jsx, frontend/components/puzzle5.jsx, frontend/components/puzzle5Clue.jsx, frontend/components/puzzle7.jsx, frontend/components/puzzle7Clue.jsx, frontend/helpers.js, server/server.py
=> update puzzle7 clues

.eslintrc.json, frontend/components/lightSwitch.jsx, frontend/components/puzzle6.jsx, frontend/components/puzzle7.jsx, frontend/components/switch.jsx
=> update to new switch for puzzle7

frontend/components/puzzle6.jsx, frontend/components/puzzleA.jsx
=> added a border on selection

frontend/components/base.jsx, frontend/components/hint.jsx, frontend/components/home.jsx, frontend/components/person0.jsx, frontend/components/puzzle1.jsx
fixes https://github.com/iamsammak/thehuntgame/issues/165
fixes https://github.com/iamsammak/thehuntgame/issues/142
=> text updates

frontend/components/hint.jsx, frontend/components/person0.jsx, frontend/components/puzzle4.jsx, frontend/components/puzzle7.jsx, frontend/components/puzzleA.jsx, server/server.py
fixes https://github.com/iamsammak/thehuntgame/issues/173
fixes https://github.com/iamsammak/thehuntgame/issues/176
fixes https://github.com/iamsammak/thehuntgame/issues/178
fixes https://github.com/iamsammak/thehuntgame/issues/180
fixes https://github.com/iamsammak/thehuntgame/issues/181
=> update hint behavior and puzzle 7

frontend/components/puzzle1.jsx, frontend/components/puzzle2.jsx, frontend/components/puzzle3.jsx, frontend/components/puzzle5.jsx, server/server.py
fixes https://github.com/iamsammak/thehuntgame/issues/174
=> updates to puzzle3

frontend/components/app.jsx, frontend/components/base.jsx, frontend/components/person1.jsx, frontend/components/puzzle1.jsx, frontend/components/puzzle2.jsx, frontend/components/puzzle3.jsx, frontend/components/puzzle4.jsx, frontend/components/puzzle4Clue.jsx, frontend/components/puzzle5.jsx, frontend/components/puzzle6.jsx, frontend/components/puzzle7.jsx, frontend/components/puzzle8.jsx, frontend/components/puzzleA.jsx, frontend/components/puzzleB.jsx, frontend/components/speechBubble.jsx, frontend/constants.js, frontend/wrappers.jsx, server/server.py
should make it more obvious when someone is speaking
had to change the background to a light gray. thoughts?
=> add speech bubbles

frontend/components/puzzle6.jsx
related to https://github.com/iamsammak/thehuntgame/issues/59
=> puzzle6 outer borders same width

server/server.py
Handles socket reconnects when the server is restarted. This is in preparation for https://github.com/iamsammak/thehuntgame/issues/33
=> handle socket reconnects

frontend/components/puzzle1.jsx, frontend/components/puzzle2.jsx, frontend/components/puzzle3.jsx, frontend/components/puzzle4.jsx, frontend/components/puzzle5.jsx, frontend/components/puzzle6.jsx, frontend/components/puzzle7.jsx, frontend/components/puzzle8.jsx, frontend/components/puzzleA.jsx, frontend/components/puzzleB.jsx, frontend/components/speechBubble.jsx, frontend/wrappers.jsx
adds the expected amount of spacing for the error and correct cases. this should help with "hidden" message if the user scrolls to the bottom, compared to before where it should "create" the space for it at the bottom
fixes https://github.com/iamsammak/thehuntgame/issues/121
=> add expected spacing

server/server.py
moves all GAME_STATE and CLIENT access to methods that we can replace when we swap out how we store the data. This is in preparation for https://github.com/iamsammak/thehuntgame/issues/33
=> refactor state data access in preparation for swapping out data store

frontend/components/app.jsx, frontend/components/main.jsx
=> Home screen refactor

frontend/components/puzzle8.jsx
fixes https://github.com/iamsammak/thehuntgame/issues/202
=> add last checkpoint for puzzle8

server/server.py
changed cipher shift to be fixed at 30
=> changed cipher shift to 30

frontend/components/app.jsx
fixes https://github.com/iamsammak/thehuntgame/issues/196
=> handle leaving and coming back and having no table

frontend/components/puzzle7Clue.jsx
=> clearly indicate what number the clue is referring to

frontend/components/app.jsx, package.json, server/server.py
fixes https://github.com/iamsammak/thehuntgame/issues/207
=> remove notifications

frontend/components/app.jsx, server/server.py
tested with chris's phone, seems like it could be an ios issue? weird though cause i think ning had the same issue and he's an android user ¯\_(ツ)_/¯
fixes https://github.com/iamsammak/thehuntgame/issues/209
=> fix connection issues (hopefully!)

frontend/components/root.jsx
fixes https://github.com/iamsammak/thehuntgame/issues/200
=> scroll to top on nav

frontend/components/puzzle7Clue.jsx
fixes https://github.com/iamsammak/thehuntgame/issues/219
=> update puzzle 7 clues

frontend/components/base.jsx, frontend/components/hint.jsx, frontend/components/puzzle3.jsx, server/server.py
fixes https://github.com/iamsammak/thehuntgame/issues/206
=> puzzle 3 updates

frontend/components/hint.jsx, frontend/components/puzzle4.jsx
fixes https://github.com/iamsammak/thehuntgame/issues/205
=> puzzle 4 updates

frontend/components/puzzle5.jsx, frontend/components/puzzleA.jsx
fixes https://github.com/iamsammak/thehuntgame/issues/224
=> involve christine in some prompts

frontend/components/puzzle8.jsx, frontend/components/root.jsx
fixes https://github.com/iamsammak/thehuntgame/issues/218
=> puzzle 8 updates

frontend/components/puzzle.jsx, frontend/components/submit.jsx
fixes https://github.com/iamsammak/thehuntgame/issues/229
fixes https://github.com/iamsammak/thehuntgame/issues/227
=> fix input zoom on ios, cleanup some unused code

frontend/components/puzzle8.jsx
fixes https://github.com/iamsammak/thehuntgame/issues/230
=> remove colors from puzzle8

frontend/components/hint.jsx, frontend/components/main.jsx, frontend/components/root.jsx
fixes https://github.com/iamsammak/thehuntgame/issues/235
=> switch to hint icon

frontend/components/puzzle4.jsx, frontend/components/puzzle8.jsx
noticed that the incorrect messages aren't displayed for very long, and since we updated the text to be longer, it might take longer to read
=> increase timeouts

frontend/components/hint.jsx, frontend/components/main.jsx, frontend/components/person0.jsx, frontend/helpers.js
fixes https://github.com/iamsammak/thehuntgame/issues/247
=> only show hint icon when a hint is actually available

frontend/components/admin.jsx, server/server.py
fixes https://github.com/iamsammak/thehuntgame/issues/246
=> improve admin page

frontend/components/home.jsx, frontend/components/puzzle1.jsx, server/server.py
fixes https://github.com/iamsammak/thehuntgame/issues/199
* sets answer
* changes puzzle1 to use circular format
* update table number validation
=> changes related to total number of tables

frontend/components/admin.jsx
fixes https://github.com/iamsammak/thehuntgame/issues/261
=> sort puzzles on admin page

frontend/components/puzzle1.jsx, frontend/components/puzzle2.jsx, frontend/components/puzzle3.jsx, frontend/components/puzzle5.jsx, frontend/components/submit.jsx
should fix the invalid DOM errors
=> move margin spacing to inside the submit component

frontend/components/puzzle3.jsx, frontend/components/puzzle4.jsx
fixes https://github.com/iamsammak/thehuntgame/issues/243
=> update line spacing after text updates

frontend/components/puzzle3.jsx
related to https://github.com/iamsammak/thehuntgame/issues/265
still waiting on the exact symbols
=> update puzzle3 with symbols

frontend/components/puzzle8.jsx
fixes https://github.com/iamsammak/thehuntgame/issues/275
=> update puzzle 8 error text

frontend/components/admin.jsx, server/server.py
related to https://github.com/iamsammak/thehuntgame/issues/77
=> allow hide/reveal of answers on admin page

frontend/components/admin.jsx
fixes a bug where the actual data wasn't using the sorted data so it wasn't aligned with the headers
=> fix admin page sorting bug

frontend/components/puzzle3.jsx, frontend/components/root.jsx, frontend/constants.js
fixes https://github.com/iamsammak/thehuntgame/issues/265
=> add in actual icons/colors for puzzle 3

frontend/components/puzzleB.jsx
fixes https://github.com/iamsammak/thehuntgame/issues/270
=> update puzzle B case

frontend/components/puzzle4.jsx
fixes https://github.com/iamsammak/thehuntgame/issues/268
=> update safe colors to be more visible
